export const data = [
  {
    id: 1,
    productClass: "Ipsum Name",
    orderId: "AG-FG-022",
    destination: "D9011",
    transMod: "SF-Trucket 44ft",
    category: "Due",
    priority: "High",
    delayed: "-15 Days",
    sku: 28,
    itemCost: "12/12/2019",
    isDisabled: false,
  },
  {
    id: 2,
    productClass: "Ipsum Name1",
    orderId: "AG-FG-023",
    destination: "D9012",
    transMod: "SF-Trucket 45ft",
    category: "Due",
    priority: "Low",
    delayed: "-4 Days",
    sku: 22,
    itemCost: "12/11/2019",
    isDisabled: false,
  },
  {
    id: 3,
    productClass: "Ipsum Name3",
    orderId: "BG-FG-022",
    destination: "C9011",
    transMod: "DF-Trucket 44ft",
    category: "Due",
    priority: "High",
    delayed: "-15 Days",
    sku: 32,
    itemCost: "12/12/2019",
    isDisabled: false,
  },
  {
    id: 4,
    productClass: "Ipsum Name4",
    orderId: "BG-FG-022",
    destination: "E9011",
    transMod: "AF-Trucket 44ft",
    category: "Due",
    priority: "Medium",
    delayed: "-12 Days",
    sku: 21,
    itemCost: "12/12/2019",
    isDisabled: false,
  },
  {
    id: 5,
    productClass: "Ipsum Name5",
    orderId: "DG-FG-022",
    destination: "B9011",
    transMod: "SF-Trucket 66ft",
    category: "Due",
    priority: "Low",
    delayed: "-2 Days",
    sku: 26,
    itemCost: "12/12/2019",
    isDisabled: false,
  },
];
